locationsInfo = {
    "Crasters Keep": {
        "lType": "location",
        "lId": 1,
        "lName": "Crasters Keep",
        "lBuyPrice": 60,
        "lRent": (2, 10, 30, 90, 160, 250),
        "lMortgage": 30,
        "lBuildPrice": 50,
        "lBuildings": 0,
        "lRentSplits": "",
        "lRentDiscounts": "",
        "lStatus": "free",
        "lOwnerId": 0
    },
    "The Fist of the First Men": {
        "lType": "location",
        "lId": 2,
        "lName": "The Fist of the First Men",
        "lBuyPrice": 60,
        "lRent": (4, 20, 60, 180, 320, 450),
        "lMortgage": 30,
        "lBuildPrice": 50,
        "lBuildings": 0,
        "lRentSplits": "",
        "lRentDiscounts": "",
        "lStatus": "free",
        "lOwnerId": 0
    },
    "The Nightfort": {
        "lType": "location",
        "lId": 3,
        "lName": "The Nightfort",
        "lBuyPrice": 100,
        "lRent": (6, 30, 90, 270, 400, 550),
        "lMortgage": 50,
        "lBuildPrice": 50,
        "lBuildings": 0,
        "lRentSplits": "",
        "lRentDiscounts": "",
        "lStatus": "free",
        "lOwnerId": 0
    },
    "Moles Town": {
        "lType": "location",
        "lId": 4,
        "lName": "Moles Town",
        "lBuyPrice": 100,
        "lRent": (6, 30, 90, 270, 400, 550),
        "lMortgage": 50,
        "lBuildPrice": 50,
        "lBuildings": 0,
        "lRentSplits": "",
        "lRentDiscounts": "",
        "lStatus": "free",
        "lOwnerId": 0
    },
    "The Inn at the Crossroads": {
        "lType": "location",
        "lId": 5,
        "lName": "The Inn at the Crossroads",
        "lBuyPrice": 120,
        "lRent": (8, 40, 100, 300, 450, 600),
        "lMortgage": 60,
        "lBuildPrice": 50,
        "lBuildings": 0,
        "lRentSplits": "",
        "lRentDiscounts": "",
        "lStatus": "free",
        "lOwnerId": 0
    },
    "Vaes Dothrak": {
        "lType": "location",
        "lId": 6,
        "lName": "Vaes Dothrak",
        "lBuyPrice": 140,
        "lRent": (10, 50, 150, 450, 625, 750),
        "lMortgage": 70,
        "lBuildPrice": 100,
        "lBuildings": 0,
        "lRentSplits": "",
        "lRentDiscounts": "",
        "lStatus": "free",
        "lOwnerId": 0
    },
    "Qarth": {
        "lType": "location",
        "lId": 7,
        "lName": "Qarth",
        "lBuyPrice": 140,
        "lRent": (10, 50, 150, 450, 625, 750),
        "lMortgage": 70,
        "lBuildPrice": 100,
        "lBuildings": 0,
        "lRentSplits": "",
        "lRentDiscounts": "",
        "lStatus": "free",
        "lOwnerId": 0
    },
    "Pentos": {
        "lType": "location",
        "lId": 8,
        "lName": "Pentos",
        "lBuyPrice": 160,
        "lRent": (12, 60, 180, 500, 700, 900),
        "lMortgage": 80,
        "lBuildPrice": 100,
        "lBuildings": 0,
        "lRentSplits": "",
        "lRentDiscounts": "",
        "lStatus": "free",
        "lOwnerId": 0
    },
    "The Eyrie": {
        "lType": "location",
        "lId": 9,
        "lName": "The Eyrie",
        "lBuyPrice": 180,
        "lRent": (14, 70, 200, 550, 750, 950),
        "lMortgage": 90,
        "lBuildPrice": 100,
        "lBuildings": 0,
        "lRentSplits": "",
        "lRentDiscounts": "",
        "lStatus": "free",
        "lOwnerId": 0
    },
    "Dragonstone": {
        "lType": "location",
        "lId": 10,
        "lName": "Dragonstone",
        "lBuyPrice": 180,
        "lRent": (14, 70, 200, 550, 750, 950),
        "lMortgage": 90,
        "lBuildPrice": 100,
        "lBuildings": 0,
        "lRentSplits": "",
        "lRentDiscounts": "",
        "lStatus": "free",
        "lOwnerId": 0
    },
    "Moat Caitlyn": {
        "lType": "location",
        "lId": 11,
        "lName": "Moat Caitlyn",
        "lBuyPrice": 200,
        "lRent": (16, 80, 220, 600, 800, 1000),
        "lMortgage": 100,
        "lBuildPrice": 100,
        "lBuildings": 0,
        "lRentSplits": "",
        "lRentDiscounts": "",
        "lStatus": "free",
        "lOwnerId": 0
    },
    "Harrenhal": {
        "lType": "location",
        "lId": 12,
        "lName": "Harrenhal",
        "lBuyPrice": 220,
        "lRent": (18, 90, 250, 700, 875, 1050),
        "lMortgage": 110,
        "lBuildPrice": 150,
        "lBuildings": 0,
        "lRentSplits": "",
        "lRentDiscounts": "",
        "lStatus": "free",
        "lOwnerId": 0
    },
    "The Dreadfort": {
        "lType": "location",
        "lId": 13,
        "lName": "The Dreadfort",
        "lBuyPrice": 220,
        "lRent": (18, 90, 250, 700, 870, 1050),
        "lMortgage": 110,
        "lBuildPrice": 150,
        "lBuildings": 0,
        "lRentSplits": "",
        "lRentDiscounts": "",
        "lStatus": "free",
        "lOwnerId": 0
    },
    "The Twins": {
        "lType": "location",
        "lId": 14,
        "lName": "The Twins",
        "lBuyPrice": 240,
        "lRent": (20, 100, 300, 750, 925, 1100),
        "lMortgage": 120,
        "lBuildPrice": 150,
        "lBuildings": 0,
        "lRentSplits": "",
        "lRentDiscounts": "",
        "lStatus": "free",
        "lOwnerId": 0
    },
    "Astapor": {
        "lType": "location",
        "lId": 15,
        "lName": "Astapor",
        "lBuyPrice": 260,
        "lRent": (22, 110, 330, 800, 975, 1150),
        "lMortgage": 130,
        "lBuildPrice": 150,
        "lBuildings": 0,
        "lRentSplits": "",
        "lRentDiscounts": "",
        "lStatus": "free",
        "lOwnerId": 0
    },
    "Yunkai": {
        "lType": "location",
        "lId": 16,
        "lName": "Yunkai",
        "lBuyPrice": 260,
        "lRent": (22, 110, 330, 800, 975, 1150),
        "lMortgage": 130,
        "lBuildPrice": 150,
        "lBuildings": 0,
        "lRentSplits": "",
        "lRentDiscounts": "",
        "lStatus": "free",
        "lOwnerId": 0
    },
    "Meereen": {
        "lType": "location",
        "lId": 17,
        "lName": "Meereen",
        "lBuyPrice": 280,
        "lRent": (24, 120, 360, 850, 1025, 1200),
        "lMortgage": 140,
        "lBuildPrice": 150,
        "lBuildings": 0,
        "lRentSplits": "",
        "lRentDiscounts": "",
        "lStatus": "free",
        "lOwnerId": 0
    },
    "Castle Black": {
        "lType": "location",
        "lId": 18,
        "lName": "Castle Black",
        "lBuyPrice": 300,
        "lRent": (26, 130, 390, 900, 1100, 1275),
        "lMortgage": 150,
        "lBuildPrice": 200,
        "lBuildings": 0,
        "lRentSplits": "",
        "lRentDiscounts": "",
        "lStatus": "free",
        "lOwnerId": 0
    },
    "Pyke": {
        "lType": "location",
        "lId": 19,
        "lName": "Pyke",
        "lBuyPrice": 300,
        "lRent": (26, 130, 390, 900, 1100, 1275),
        "lMortgage": 150,
        "lBuildPrice": 200,
        "lBuildings": 0,
        "lRentSplits": "",
        "lRentDiscounts": "",
        "lStatus": "free",
        "lOwnerId": 0
    },
    "Winterfell": {
        "lType": "location",
        "lId": 20,
        "lName": "Winterfell",
        "lBuyPrice": 320,
        "lRent": (28, 150, 450, 1000, 1200, 1400),
        "lMortgage": 160,
        "lBuildPrice": 200,
        "lBuildings": 0,
        "lRentSplits": "",
        "lRentDiscounts": "",
        "lStatus": "free",
        "lOwnerId": 0
    },
    "Braavos": {
        "lType": "location",
        "lId": 21,
        "lName": "Braavos",
        "lBuyPrice": 350,
        "lRent": (35, 175, 500, 1100, 1300, 1500),
        "lMortgage": 175,
        "lBuildPrice": 200,
        "lBuildings": 0,
        "lRentSplits": "",
        "lRentDiscounts": "",
        "lStatus": "free",
        "lOwnerId": 0
    },
    "Kings Landing": {
        "lType": "location",
        "lId": 22,
        "lName": "Kings Landing",
        "lBuyPrice": 400,
        "lRent": (50, 200, 600, 1400, 1700, 2000),
        "lMortgage": 200,
        "lBuildPrice": 200,
        "lBuildings": 0,
        "lRentSplits": "",
        "lRentDiscounts": "",
        "lStatus": "free",
        "lOwnerId": 0
    }
}

housesInfo = {
    "Targaryen": {
        "lType": "house",
        "lId": 1,
        "lName": "Targaryen",
        "lBuyPrice": 200,
        "lRent": (25, 50, 100, 200),
        "lMortgage": 100,
        "lStatus": "free",
        "lOwnerId": 0
    },
    "Stark": {
        "lType": "house",
        "lId": 2,
        "lName": "Stark",
        "lBuyPrice": 200,
        "lRent": (25, 50, 100, 200),
        "lMortgage": 100,
        "lStatus": "free",
        "lOwnerId": 0
    },
    "Lannister": {
        "lType": "house",
        "lId": 3,
        "lName": "Lannister",
        "lBuyPrice": 200,
        "lRent": (25, 50, 100, 200),
        "lMortgage": 100,
        "lStatus": "free",
        "lOwnerId": 0
    },
    "Baratheon": {
        "lType": "house",
        "lId": 4,
        "lName": "Baratheon",
        "lBuyPrice": 200,
        "lRent": (25, 50, 100, 200),
        "lMortgage": 100,
        "lStatus": "free",
        "lOwnerId": 0
    }
}

poiInfo = {
    "The Wall": {
        "lType": "poi",
        "lId": 1,
        "lName": "The Wall",
        "lBuyPrice": 150,
        "lRent": (4, 10),
        "lMortgage": 75,
        "lStatus": "free",
        "lOwnerId": 0
    },
    "The Red Waste": {
        "lType": "poi",
        "lId": 2,
        "lName": "The Red Waste",
        "lBuyPrice": 150,
        "lRent": (4, 10),
        "lMortgage": 75,
        "lStatus": "free",
        "lOwnerId": 0
    },
}
