locationsInfo = {
    "Crasters Keep": {
        "id": 1,
        "name": "Crasters Keep",
        "buyPrice": 60,
        "rent": (2, 10, 30, 90, 160, 250),
        "mortgage": 30,
        "buildPrice": 50,
        "buildings": 0,
        "rentSplits": {},
        "rentDiscounts": {},
        "status": "free",
        "ownerId": 0
    },
    "The Fist of the First Men": {
        "id": 2,
        "name": "The Fist of the First Men",
        "buyPrice": 60,
        "rent": (4, 20, 60, 180, 320, 450),
        "mortgage": 30,
        "buildPrice": 50,
        "buildings": 0,
        "rentSplits": {},
        "rentDiscounts": {},
        "status": "free",
        "ownerId": 0
    },
    "The Nightfort": {
        "id": 3,
        "name": "The Nightfort",
        "buyPrice": 100,
        "rent": (6, 30, 90, 270, 400, 550),
        "mortgage": 50,
        "buildPrice": 50,
        "buildings": 0,
        "rentSplits": {},
        "rentDiscounts": {},
        "status": "free",
        "ownerId": 0
    },
    "Moles Town": {
        "id": 4,
        "name": "Moles Town",
        "buyPrice": 100,
        "rent": (6, 30, 90, 270, 400, 550),
        "mortgage": 50,
        "buildPrice": 50,
        "buildings": 0,
        "rentSplits": {},
        "rentDiscounts": {},
        "status": "free",
        "ownerId": 0
    },
    "The Inn at the Crossroads": {
        "id": 5,
        "name": "The Inn at the Crossroads",
        "buyPrice": 120,
        "rent": (8, 40, 100, 300, 450, 600),
        "mortgage": 60,
        "buildPrice": 50,
        "buildings": 0,
        "rentSplits": {},
        "rentDiscounts": {},
        "status": "free",
        "ownerId": 0
    },
    "Vaes Dothrak": {
        "id": 6,
        "name": "Vaes Dothrak",
        "buyPrice": 140,
        "rent": (10, 50, 150, 450, 625, 750),
        "mortgage": 70,
        "buildPrice": 100,
        "buildings": 0,
        "rentSplits": {},
        "rentDiscounts": {},
        "status": "free",
        "ownerId": 0
    },
    "Qarth": {
        "id": 7,
        "name": "Qarth",
        "buyPrice": 140,
        "rent": (10, 50, 150, 450, 625, 750),
        "mortgage": 70,
        "buildPrice": 100,
        "buildings": 0,
        "rentSplits": {},
        "rentDiscounts": {},
        "status": "free",
        "ownerId": 0
    },
    "Pentos": {
        "id": 8,
        "name": "Pentos",
        "buyPrice": 160,
        "rent": (12, 60, 180, 500, 700, 900),
        "mortgage": 80,
        "buildPrice": 100,
        "buildings": 0,
        "rentSplits": {},
        "rentDiscounts": {},
        "status": "free",
        "ownerId": 0
    },
    "The Eyrie": {
        "id": 9,
        "name": "The Eyrie",
        "buyPrice": 180,
        "rent": (14, 70, 200, 550, 750, 950),
        "mortgage": 90,
        "buildPrice": 100,
        "buildings": 0,
        "rentSplits": {},
        "rentDiscounts": {},
        "status": "free",
        "ownerId": 0
    },
    "Dragonstone": {
        "id": 10,
        "name": "Dragonstone",
        "buyPrice": 180,
        "rent": (14, 70, 200, 550, 750, 950),
        "mortgage": 90,
        "buildPrice": 100,
        "buildings": 0,
        "rentSplits": {},
        "rentDiscounts": {},
        "status": "free",
        "ownerId": 0
    },
    "Moat Caitlyn": {
        "id": 11,
        "name": "Moat Caitlyn",
        "buyPrice": 200,
        "rent": (16, 80, 220, 600, 800, 1000),
        "mortgage": 100,
        "buildPrice": 100,
        "buildings": 0,
        "rentSplits": {},
        "rentDiscounts": {},
        "status": "free",
        "ownerId": 0
    },
    "Harrenhal": {
        "id": 12,
        "name": "Harrenhal",
        "buyPrice": 220,
        "rent": (18, 90, 250, 700, 875, 1050),
        "mortgage": 110,
        "buildPrice": 150,
        "buildings": 0,
        "rentSplits": {},
        "rentDiscounts": {},
        "status": "free",
        "ownerId": 0
    },
    "The Dreadfort": {
        "id": 13,
        "name": "The Dreadfort",
        "buyPrice": 220,
        "rent": (18, 90, 250, 700, 870, 1050),
        "mortgage": 110,
        "buildPrice": 150,
        "buildings": 0,
        "rentSplits": {},
        "rentDiscounts": {},
        "status": "free",
        "ownerId": 0
    },
    "The Twins": {
        "id": 14,
        "name": "The Twins",
        "buyPrice": 240,
        "rent": (20, 100, 300, 750, 925, 1100),
        "mortgage": 120,
        "buildPrice": 150,
        "buildings": 0,
        "rentSplits": {},
        "rentDiscounts": {},
        "status": "free",
        "ownerId": 0
    },
    "Astapor": {
        "id": 15,
        "name": "Astapor",
        "buyPrice": 260,
        "rent": (22, 110, 330, 800, 975, 1150),
        "mortgage": 130,
        "buildPrice": 150,
        "buildings": 0,
        "rentSplits": {},
        "rentDiscounts": {},
        "status": "free",
        "ownerId": 0
    },
    "Yunkai": {
        "id": 16,
        "name": "Yunkai",
        "buyPrice": 260,
        "rent": (22, 110, 330, 800, 975, 1150),
        "mortgage": 130,
        "buildPrice": 150,
        "buildings": 0,
        "rentSplits": {},
        "rentDiscounts": {},
        "status": "free",
        "ownerId": 0
    },
    "Meereen": {
        "id": 17,
        "name": "Meereen",
        "buyPrice": 280,
        "rent": (24, 120, 360, 850, 1025, 1200),
        "mortgage": 140,
        "buildPrice": 150,
        "buildings": 0,
        "rentSplits": {},
        "rentDiscounts": {},
        "status": "free",
        "ownerId": 0
    },
    "Castle Black": {
        "id": 18,
        "name": "Castle Black",
        "buyPrice": 300,
        "rent": (26, 130, 390, 900, 1100, 1275),
        "mortgage": 150,
        "buildPrice": 200,
        "buildings": 0,
        "rentSplits": {},
        "rentDiscounts": {},
        "status": "free",
        "ownerId": 0
    },
    "Pyke": {
        "id": 19,
        "name": "Pyke",
        "buyPrice": 300,
        "rent": (26, 130, 390, 900, 1100, 1275),
        "mortgage": 150,
        "buildPrice": 200,
        "buildings": 0,
        "rentSplits": {},
        "rentDiscounts": {},
        "status": "free",
        "ownerId": 0
    },
    "Winterfell": {
        "id": 20,
        "name": "Winterfell",
        "buyPrice": 320,
        "rent": (28, 150, 450, 1000, 1200, 1400),
        "mortgage": 160,
        "buildPrice": 200,
        "buildings": 0,
        "rentSplits": {},
        "rentDiscounts": {},
        "status": "free",
        "ownerId": 0
    },
    "Braavos": {
        "id": 21,
        "name": "Braavos",
        "buyPrice": 350,
        "rent": (35, 175, 500, 1100, 1300, 1500),
        "mortgage": 175,
        "buildPrice": 200,
        "buildings": 0,
        "rentSplits": {},
        "rentDiscounts": {},
        "status": "free",
        "ownerId": 0
    },
    "Kings Landing": {
        "id": 22,
        "name": "Kings Landing",
        "buyPrice": 400,
        "rent": (50, 200, 600, 1400, 1700, 2000),
        "mortgage": 200,
        "buildPrice": 200,
        "buildings": 0,
        "rentSplits": {},
        "rentDiscounts": {},
        "status": "free",
        "ownerId": 0
    }
}

housesInfo = {
    "Targaryen": {
        "id": 1,
        "name": "Targaryen",
        "buyPrice": 200,
        "rent": (25, 50, 100, 200),
        "mortgage": 100,
        "status": "free",
        "ownerId": 0
    },
    "Stark": {
        "id": 2,
        "name": "Stark",
        "buyPrice": 200,
        "rent": (25, 50, 100, 200),
        "mortgage": 100,
        "status": "free",
        "ownerId": 0
    },
    "Lannister": {
        "id": 3,
        "name": "Lannister",
        "buyPrice": 200,
        "rent": (25, 50, 100, 200),
        "mortgage": 100,
        "status": "free",
        "ownerId": 0
    },
    "Baratheon": {
        "id": 4,
        "name": "Baratheon",
        "buyPrice": 200,
        "rent": (25, 50, 100, 200),
        "mortgage": 100,
        "status": "free",
        "ownerId": 0
    }
}

poiInfo = {
    "The Wall": {
        "id": 1,
        "name": "The Wall",
        "buyPrice": 150,
        "rent": (4, 10),
        "mortgage": 75,
        "status": "free",
        "ownerId": 0
    },
    "The Red Waste": {
        "id": 1,
        "name": "The Red Waste",
        "buyPrice": 150,
        "rent": (4, 10),
        "mortgage": 75,
        "status": "free",
        "ownerId": 0
    },
}
